### ISSUE TITLE
Better way to reverse string.

### ISSUE THREAD

**Issue by samlovescoding** [anneomcl/HappieChallengeCSharp#1]
`public static string Reverse( string s )
{
    char[] charArray = s.ToCharArray();
    Array.Reverse( charArray );
    return new string( charArray );
}`

Check [here](https://stackoverflow.com/questions/228038/best-way-to-reverse-a-string)

**Comment by anneomcl** [comment]
This repo is more of meant to be random problems that I find my own solution to :) Perhaps I'll go back through and revise to a "perfect" solution again sometime later.
